name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - dev-server

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Jekyll
        run: 'sudo gem install bundler && sudo bundle install && bundle exec jekyll build'
        env:
          JEKYLL_ENV: production
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASWANTHVC1 }}'
          channelId: live
          projectId: aswanthvc1
          target: aswanthvc-dev