name: Dev PR Preview CI
on: 
  pull_request:
    branches:
      - dev-server
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on:   ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          ruby-version: '3.0'
          bundler-cache: true
          cache-version: 0
      - name: Build with Jekyll
        run: bash .github/workflows/load_config.sh ${{secrets.CONTACT_SUPABASE_TOKEN}} && mkdir project && bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Cache Firebase tools
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-firebase-tools-${{ hashFiles('**/package-lock.json') }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASWANTHVC1 }}'
          projectId: aswanthvc1
          target: aswanthvc-dev
